title: "wangc的第一宇宙"
description: "用知识建立信息世界的根据地"
url: 
baseurl: ""
author: "wangc"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs